name: app_minimizer
description: A new flutter plugin project.
version: 1.0.0

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.codecity.flutter_app_minimizer
        pluginClass: FlutterAppMinimizerPlugin
      ios:
        pluginClass: FlutterAppMinimizerPlugin
